### ISSUE TITLE
Daemon throws exception and terminates when started on agent install

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/scanner-proxy#9]
When `chroma-agent` is deployed by `chroma-manager`, the `scanner-proxy` (and `device-scanner` are installed as dependencies. When the `scanner-proxy` starts it throws  exception because the agent, which is just starting, has not created the `/var/lib/chroma/settings` directory containing the  URL of the manager which is needed to address the `scanner-proxy` messages to the `device-aggregator`.

The generation of the settings directory occurs within `https://github.com/intel-hpdd/intel-manager-for-lustre\chroma-agent\chroma_agent\action_plugins\agent_setup.py` in `register_server` .

This exception usually causes the `scanner-proxy-daemon` to restart twice and then continue as expected (the end result is operational despite the exceptions).

systemd After directive should solve this problem by ensuring that scanner-proxy starts after agent  but this looks like it won't work because the chroma-agent doesn't run as a systemd unit file service (sys-v).

https://serverfault.com/questions/812584/in-systemd-whats-the-difference-between-after-and-requires

**Comment by tanabarr** [comment]
#8 https://github.com/intel-hpdd/intel-manager-for-lustre/pull/219 are both related

**Comment by jgrund** [comment]
This will be fixed by using a path unit in: #10
